### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by MargauxAlison** [morispi/HG-CoLoR#11]
Hi, 

I have some difficulties to run HG-CoLoR, it stops after few seconds.

Here is my command (I have about ~100x for short reads) : 

`HG-CoLoR --longreads $LRFASTA --shortreads $SHORTREAD --out $CORRREADS -K 100 --nproc 8 --solid 2 --bestn 40` 

 Here the slurm output :

`[Wed Feb 13 09:19:51 CET 2019] Correcting the short reads
[Wed Feb 13 09:19:57 CET 2019] Removing short reads containing weak K-mers
[Wed Feb 13 09:20:01 CET 2019] Building the graph
[Wed Feb 13 09:20:03 CET 2019] Preparing the raw long reads temporary files
Traceback (most recent call last):
  File "/usr/local/bioinfo/src/HG-CoLoR/HG-CoLoR-d476519/bin/prepareRawLongReads.py", line 12, in <module>
    out = open(sys.argv[2] + id[1:-1], "w")
FileNotFoundError: [Errno 2] No such file or directory: './HGC_3078/RawLongReads/m180221_013155_42237_c101409362550000001823304103141816_s1_p0/1434/783_15206_2_2104'
`

I looked into the ./HGC_3078/RawLongReads directory and it is void.

Here the HG-CoLoR.stderr : 

`----- QuorUM -----
----- revseq -----
Reverse and complement a nucleotide sequence
----- KMC -----
***
Stage 1: 100%
Stage 2: 100%
----- KMC_tools -----
----- KMC_dump -----
----- PgSAgen -----
`

And here the HG-CoLoR.stdout : 

`----- QuorUM -----
----- revseq -----
----- KMC -----
1st stage: 0.773835s
2nd stage: 0.259328s
Total    : 1.03316s
Tmp size : 5MB

Stats:
   No. of k-mers below min. threshold :      2211894
   No. of k-mers above max. threshold :            0
   No. of unique k-mers               :      2770468
   No. of unique counted k-mers       :       558574
   Total no. of k-mers                :      3575842
   Total no. of reads                 :        95036
   Total no. of super-k-mers          :       165740
----- KMC_tools -----
----- KMC_dump -----
----- PgSAgen -----
Reading reads set
reads count: 558574
all reads length: 55857400
reads length is constant
maxReadLength: 100
symbolsCount: 4
symbols: ACGT

Found 0 duplicates.
Start overlapping.
23649 reads left after 99 overlap
23167 reads left after 98 overlap
22775 reads left after 97 overlap
22475 reads left after 96 overlap
22173 reads left after 95 overlap
21878 reads left after 94 overlap
21614 reads left after 93 overlap
21392 reads left after 92 overlap
21130 reads left after 91 overlap
20890 reads left after 90 overlap
20674 reads left after 89 overlap
20454 reads left after 88 overlap
20266 reads left after 87 overlap
20062 reads left after 86 overlap
19870 reads left after 85 overlap
19688 reads left after 84 overlap
19538 reads left after 83 overlap
19400 reads left after 82 overlap
19232 reads left after 81 overlap
19112 reads left after 80 overlap
18982 reads left after 79 overlap
18872 reads left after 78 overlap
18752 reads left after 77 overlap
18640 reads left after 76 overlap
18536 reads left after 75 overlap
18406 reads left after 74 overlap
18292 reads left after 73 overlap
18186 reads left after 72 overlap
18112 reads left after 71 overlap
18012 reads left after 70 overlap
17922 reads left after 69 overlap
17850 reads left after 68 overlap
17776 reads left after 67 overlap
17702 reads left after 66 overlap
17604 reads left after 65 overlap
17531 reads left after 64 overlap
17447 reads left after 63 overlap
17381 reads left after 62 overlap
17311 reads left after 61 overlap
17241 reads left after 60 overlap
17147 reads left after 59 overlap
17083 reads left after 58 overlap
17018 reads left after 57 overlap
16948 reads left after 56 overlap
16872 reads left after 55 overlap
16814 reads left after 54 overlap
16750 reads left after 53 overlap
16692 reads left after 52 overlap
16630 reads left after 51 overlap
16560 reads left after 50 overlap
16518 reads left after 49 overlap
16466 reads left after 48 overlap
16402 reads left after 47 overlap
16354 reads left after 46 overlap
16296 reads left after 45 overlap
16240 reads left after 44 overlap
16190 reads left after 43 overlap
16140 reads left after 42 overlap
16093 reads left after 41 overlap
16038 reads left after 40 overlap
15982 reads left after 39 overlap
15922 reads left after 38 overlap
15874 reads left after 37 overlap
15823 reads left after 36 overlap
15779 reads left after 35 overlap
15718 reads left after 34 overlap
15663 reads left after 33 overlap
15607 reads left after 32 overlap
15557 reads left after 31 overlap
15501 reads left after 30 overlap
15442 reads left after 29 overlap
15400 reads left after 28 overlap
15322 reads left after 27 overlap
15272 reads left after 26 overlap
15204 reads left after 25 overlap
15153 reads left after 24 overlap
15097 reads left after 23 overlap
15048 reads left after 22 overlap
15002 reads left after 21 overlap
14952 reads left after 20 overlap
14908 reads left after 19 overlap
14853 reads left after 18 overlap
14805 reads left after 17 overlap
14742 reads left after 16 overlap
14687 reads left after 15 overlap
14600 reads left after 14 overlap
14515 reads left after 13 overlap
14379 reads left after 12 overlap
14079 reads left after 11 overlap
13431 reads left after 10 overlap
12091 reads left after 9 overlap
9262 reads left after 8 overlap
5797 reads left after 7 overlap
3020 reads left after 6 overlap
1761 reads left after 5 overlap
1089 reads left after 4 overlap
897 reads left after 3 overlap
596 reads left after 2 overlap
468 reads left after 1 overlap
468 pseudo-genome components
Overlapping done in 690 msec

2159117 bytes after overlapping
468 pseudo-genome components
0 single reads
Pseudogenome assembled in 120 msec

Found 41192 reads containing duplicate 11-mers in 30 msec!
SA creation start.
Written 5757912 bytes
Written 2879356 bytes
SAIS generation time 180 msec!
SA generation time 490 msec!
4194305 elements in SA lookup
SA LUT generation time 80 msec!
Written 2159217 bytes
Written 5027175 bytes
Written 8636476 bytes
Written 16777220 bytes
`

Could you help me please?

Thanks,

**Comment by morispi** [comment]
Hi,

Seems to be caused by the fact your long reads contain '/' characters in their headers.

Could you please try to switch those '/' to '_' or '-' and rerun HG-CoLoR?
I think it should do the trick.

Pierre

**Comment by MargauxAlison** [comment]
Hi,
I modified my fasta and indeed it is working.
Thank you for your answer,
Margaux-Alison
