### ISSUE TITLE
tmp files deleted before job is finished

### ISSUE THREAD

**Issue by JuliaLopezDelgado** [morispi/HG-CoLoR#17]
Hello. I am trying to run the following code in a SGE script:
`HG-CoLoR --longreads $long_reads --shortreads $short_reads --tmpdir ./tmp --out HGCcor_long_reads.fasta --nproc 48`

I get the following error, which I think happens because the temporary files are deleted before processing is complete:
`Traceback (most recent call last):
  File "/home/home02/bsjld/.conda/envs/genomeassembly/bin/filterShortReads.py", line 7, in <module>
    f = open(sys.argv[1])
FileNotFoundError: [Errno 2] No such file or directory: './tmp/quorum_corrected.fa'
sed: can't read ./tmp/RC_long_quorum_corrected.fa: No such file or directory
cat: ./tmp/RC_long_quorum_corrected.fa: No such file or directory
mv: cannot stat ‘./tmp/good_long_quorum_corrected.fa’: No such file or directory
/home/home02/bsjld/.conda/envs/genomeassembly/bin/HG-CoLoR: line 217: 130788 Floating point exception(core dumped) PgSAgen_hgcolor $tmpdir/"$k-mers-$SR" $tmpdir/"$k-mers-$SR" >> HG-CoLoR.stdout 2>> HG-CoLoR.stderr
Traceback (most recent call last):
  File "/home/home02/bsjld/.conda/envs/genomeassembly/bin/filterOutShortAlignments.py", line 36, in <module>
    out.write(finalString)
NameError: name 'out' is not defined
`
Could you please help me with this issue?
Thank you in advance.

**Comment by morispi** [comment]
Hey,

It seems like you are using a conda installed version of HG-CoLoR.
Unfortunately, I do not maintain the conda version myself.

Could you please try to clone and install HG-CoLoR from the github repo? This should resolve your problem.

Cheers,
Pierre

**Comment by JuliaLopezDelgado** [comment]
Hello,
Sorry for the late reply!
I re-installed it from the github repo instead of conda, and removed the .fasta from the resultPrefix and it works fine now. 
Thank you,
Julia
