### ISSUE TITLE
Run fails and only prints 'Correcting the short reads'

### ISSUE THREAD

**Issue by JuliaLopezDelgado** [morispi/HG-CoLoR#19]
Hello,

I'm running HgColor (installed from the github repo) to correct Nanopore reads (~30x) using Illumina reads (~150x):
`/home/bin/HG_CoLoR/HG_CoLoR --longreads ONT_filtered.fasta --shortreads short.fastq --tmpdir ./tmp --out ONT_HgColor --solid 2 --bestn 30 --nproc 48 -K 101`

However, it only runs for one second and stops, and prints the message: `Correcting the short reads`. The output directory doesn't contain any corrected reads. 

What could be causing this issue?

Thanks,
Julia

**Comment by morispi** [comment]
Hello,

This seems to indicate there's an issue with QuorUM. Do you have it installed and available through your PATH? If not, I advise you to follow the "Requirements" section of HG-CoLoR's README, all requirements and where to dowload them are provided here.

Please do contact me again if you encounter further issues.

Best,
Pierre

**Comment by JuliaLopezDelgado** [comment]
Hello,

I specified the path and it works fine now! Thanks for your help. 

Best wishes,
Julia
